### ISSUE TITLE
mix prolog fails

### ISSUE THREAD

**Issue by mlliarm** [sasagawa888/Elxlog#3]
Hi there ! Great project, but I'm having some issues.

I run on a Lubuntu 18.04.3 LTS.

The version of Elixir I get by running `elixir -v` is:
`Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]`

When I run `mix prolog` inside the Elxlog directory I get:
`** (Mix) Invalid Elixir version requirement ~> 1.7 in mix.exs file`

Any ideas?

**Comment by sasagawa888** [comment]
I rewritten the version information of mix.exs as follows. Please try again.
def project do
    [
      app: :elxlog,
      version: "0.1.4",
      elixir: "~> 1.4",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

**Comment by mlliarm** [comment]
Hi there. 
Thank you. I did a git pull, and `mix prolog` and got the same result:

`** (Mix) Invalid Elixir version requirement ~> 1.4 in mix.exs file`

I might be doing something wrong here, so let me explain what I did.

0. Installed elixir with `sudo apt-get install elixir`.
1. Cloned the repository
2. Went inside Elxlog
3. Did `mix prolog`

If it's relevant, when I do `elixir -v` a crush dump file is being generated:

```
{"init terminating in do_boot",{{badmatch,error},[{'Elixir.System',build,0,[{file,"lib/system.ex"},{line,172}]},{'Elixir.System',build_info,0,[{file,"lib/system.ex"},{line,164}]},{'Elixir.Kernel.CLI',parse_shared,2,[{file,"lib/kernel/cli.ex"},{line,153}]},{'Elixir.Kernel.CLI','shared_option?',3,[{file,"lib/kernel/cli.ex"},{line,113}]},{'Elixir.Kernel.CLI',main,1,[{file,"lib/kernel/cli.ex"},{line,14}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({{badmatch,error},[{Elixir.System,build,0,[{_},{_}]},{Elixir.System,build_info,0,[{_},{_}]},{Elixir.Kernel.CLI,parse_shared,2,[{_},{_}]},{Elixir.Kernel.CLI,shared_option?,

Crash dump is being written to: erl_crash.dump...done
```

Perhaps something is wrong with my Erlang ?

**Comment by sasagawa888** [comment]
Startup is mix elxlog.
Please enter the following from the OS prompt.

mix elxlog

e.g.
$ mix elxlog
Elxlog ver0.14
?- write(1).
1true
?- halt().
goodbye

**Comment by mlliarm** [comment]
Thanks for getting back to me.

I just tried `mix elxlog` and I keep getting:

``(Mix) Invalid Elixir version requirement ~> 1.4 in mix.exs file``

I'm sorry for bothering you !

**Comment by sasagawa888** [comment]
I guess it's because your Elixir version is old. Please update to the latest version.

**Comment by mlliarm** [comment]
You are right. It's an older version provided by the repositories. I'll download the latest and let you know. Thanks !

**Comment by mlliarm** [comment]
It's working now. Thank you !
